# Generated by Django 5.1.2 on 2024-10-25 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno', '0001_initial'),
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignacionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignacion', models.DateField(auto_now=True)),
                ('fechaResolucion', models.DateField()),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=2)),
                ('observaciones', models.TextField(max_length=200)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.examen')),
            ],
        ),
    ]
