# Generated by Django 5.1.2 on 2024-10-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacionExamen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionexamen',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
