# Generated by Django 5.1.2 on 2024-10-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacionExamen', '0002_alter_asignacionexamen_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionexamen',
            name='fechaResolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionexamen',
            name='observaciones',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
